In [3]:
import numpy as np

X = np.random.random((50, 2))
X_centered = X - X.mean(axis=0)
U, s, V = np.linalg.svd(X_centered)
c1 = V.T[:, 0]
c2 = V.T[:, 1]

W2 = V.T[:, :1]
W2D = X_centered.dot(W2)

In [4]:
c1

array([-0.36270925, -0.93190235])

In [5]:
c2

array([-0.93190235,  0.36270925])

In [6]:
V

array([[-0.36270925, -0.93190235],
       [-0.93190235,  0.36270925]])

In [7]:
W2 = V.T[:, :1]

In [8]:
W2

array([[-0.36270925],
       [-0.93190235]])

In [9]:
W2D = X_centered.dot(W2)

In [10]:
W2D

array([[-0.39233402],
       [-0.28857368],
       [-0.10617037],
       [-0.4216964 ],
       [-0.22465363],
       [-0.02929604],
       [ 0.1023748 ],
       [-0.22731089],
       [ 0.13695384],
       [-0.28441965],
       [-0.50664722],
       [-0.25836477],
       [ 0.07538414],
       [ 0.09381625],
       [ 0.49073958],
       [-0.21384665],
       [-0.65896483],
       [-0.20243959],
       [-0.48092725],
       [-0.05552603],
       [ 0.40991829],
       [ 0.25417749],
       [ 0.36292444],
       [ 0.1018798 ],
       [ 0.43517579],
       [ 0.25969836],
       [ 0.26738851],
       [-0.59831662],
       [-0.34862086],
       [ 0.30446757],
       [ 0.01307824],
       [ 0.12129737],
       [ 0.0827309 ],
       [-0.39829632],
       [-0.27147748],
       [ 0.36635154],
       [ 0.26462201],
       [ 0.07922015],
       [ 0.22857245],
       [ 0.40688764],
       [-0.35240263],
       [ 0.40388177],
       [-0.53987017],
       [ 0.35828378],
       [ 0.13202804],
       [ 0

In [13]:
from sklearn.decomposition import PCA

pca = PCA(n_components=1)
X2D = pca.fit_transform(X)

In [14]:
X2D

array([[ 0.39233402],
       [ 0.28857368],
       [ 0.10617037],
       [ 0.4216964 ],
       [ 0.22465363],
       [ 0.02929604],
       [-0.1023748 ],
       [ 0.22731089],
       [-0.13695384],
       [ 0.28441965],
       [ 0.50664722],
       [ 0.25836477],
       [-0.07538414],
       [-0.09381625],
       [-0.49073958],
       [ 0.21384665],
       [ 0.65896483],
       [ 0.20243959],
       [ 0.48092725],
       [ 0.05552603],
       [-0.40991829],
       [-0.25417749],
       [-0.36292444],
       [-0.1018798 ],
       [-0.43517579],
       [-0.25969836],
       [-0.26738851],
       [ 0.59831662],
       [ 0.34862086],
       [-0.30446757],
       [-0.01307824],
       [-0.12129737],
       [-0.0827309 ],
       [ 0.39829632],
       [ 0.27147748],
       [-0.36635154],
       [-0.26462201],
       [-0.07922015],
       [-0.22857245],
       [-0.40688764],
       [ 0.35240263],
       [-0.40388177],
       [ 0.53987017],
       [-0.35828378],
       [-0.13202804],
       [-0

In [15]:
pca.components_

array([[0.36270925, 0.93190235]])

In [16]:
pca.explained_variance_

array([0.1032374])

In [17]:
pca.explained_variance_ratio_

array([0.5253216])

- 增量PCA

In [21]:
import numpy as np
from sklearn.decomposition import IncrementalPCA
from sklearn.datasets import fetch_mldata

n_batches = 100
mnist = fetch_mldata('MNIST original')
X_mnist = mnist["data"]

inc_pca = IncrementalPCA(n_components=154)
for X_batch in np.array_split(X_mnist, n_batches):
    inc_pca.partial_fit(X_batch)
X_mnist_reduced = inc_pca.transform(X_mnist)

In [22]:
mnist

{'COL_NAMES': ['label', 'data'],
 'DESCR': 'mldata.org dataset: mnist-original',
 'data': array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 'target': array([0., 0., 0., ..., 9., 9., 9.])}

In [33]:
X_mnist_reduced[:5, :4]

array([[1010.4938683 ,  289.98656863, -576.13114671,  485.02735857],
       [1033.56107939,  351.21945458, -498.41164119,  554.81900289],
       [ 615.42549819,  244.23720443, -629.1356727 ,  725.08891978],
       [ 942.22176427,  245.4121022 , -868.28183244,  436.52778948],
       [1645.83442283,   80.76361962,  192.65419853,  733.62010349]])

In [34]:
X_mnist.shape

(70000, 784)

In [35]:
m, n = X_mnist.shape

In [ ]:
X_mm = np.memmap(filename, dtype="float32", mode="readonly", shape=(m, n))
batch_size = m // n_batches
inc_pca = IncrementalPCA(n_components=154, batch_size=batch_size)
inc_pca.fit(X_mm)